# 5

name: Python package

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
    - name: Debug
      run: |
        echo "github.event_name ${{ github.event_name }}"
        echo "github.ref ${{ github.ref }}"
        echo "github.event.ref ${{ github.event.ref }}"
        echo "matrix.os ${{ matrix.os }}"
        echo "matrix.python-version ${{ matrix.python-version }}"
